---
name: create_tag

'on':
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{secrets.PUSH_TOKEN}}

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.14

      - name: Set up Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2

      - name: Tag and push
        run: |
          ./create_tag.sh
...
